## Server
server:
  port: 9000

## PostgreSQL
spring:
  datasource:
    driverClassName: com.postgresql.cj.jdbc.Driver
    url: jdbc:postgresql://0.0.0.0:3306/userservice?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 111
