## Server
server:
  port: 9000

## PostgreSQL
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: 111

userservice:
  host: http://127.0.0.1
  port: 9001
  paths:
    advertisement: /advertisements/advertisement