## Server
server:
  port: 9001

## PostgreSQL
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/advertisements
    username: postgres
    password: 111

userservice:
  host: http://localhost
  port: 9000
  paths:
    user: /users/user


